services:
  ollama:
    image: ollama/ollama
    container_name: ollama
    env_file:
      - ./.env
    entrypoint: ["/bin/sh", "/entrypoint.sh"]
    volumes:
      - ollama-data:/root/.ollama
      - ./backend/Docker/ollama-entrypoint.sh:/entrypoint.sh
    ports:
      - "11435:11434"
    restart: always
    networks:
      - app-network
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - OLLAMA_NUM_GPU_LAYERS=35
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
 

volumes:
  postgres_data:
  ollama-data:
  minio_data:

networks:
  app-network:
    driver: bridge
